routes:
    home: 'Default:home'
    article: 'Default:article'
    profil: 'Default:profil'
    login: 'Security:login'
    logout: 'Security:logout'
    register: 'Security:register'
    addArticle: 'Security:addArticle'
    displayArticle: 'Default:displayArticle'
    comments: 'Security:comments'
    delComment: 'Security:delComment'
    changeMdp: 'Security:changeMdp'
    changeUsername: 'Security:changeUsername'
    editArticle: 'Default:editArticle'
    editIt: 'Security:editIt'

defaut_route: 'home'

db_config:
    name: 'flawless'
    host: 'localhost'
    user: 'root'
    pass: ''
