routes:
    home: 'Default:home'
    article: 'Default:article'
    add: 'Security:add'
    login: 'Security:login'
    logout: 'Security:logout'
    register: 'Security:register'
    comment: 'Security:comment'

defaut_route: 'home'

db_config:
    name: 'flawless'
    host: 'localhost'
    user: 'root'
    pass: ''
