routes:
    home: 'Default:home'
    about: 'Default:about'
    login: 'Security:login'
    logout: 'Security:logout'
    register: 'Security:register'

defaut_route: 'home'

db_config:
    name: 'flawless'
    host: 'localhost'
    user: 'root'
    pass: ''
